package str

import "../../abi"

// Char_Cell is a string cell of one unit in static data, laid out as String_Cell lays it out in
// the heap.
@(private)
Char_Cell :: struct {
	cell: abi.String_Cell,
	unit: u16,
}
#assert(offset_of(Char_Cell, unit) == size_of(abi.String_Cell))

// ASCII holds every one-unit string below 128, so reading one out of a text allocates nothing, as
// with the single character strings V8 keeps. Odin has no loop at compile time, hence 128 rows.
@(private, rodata)
ASCII := [128]Char_Cell {
	{cell = {type_table = STRING, length = 1}, unit = 0x00},
	{cell = {type_table = STRING, length = 1}, unit = 0x01},
	{cell = {type_table = STRING, length = 1}, unit = 0x02},
	{cell = {type_table = STRING, length = 1}, unit = 0x03},
	{cell = {type_table = STRING, length = 1}, unit = 0x04},
	{cell = {type_table = STRING, length = 1}, unit = 0x05},
	{cell = {type_table = STRING, length = 1}, unit = 0x06},
	{cell = {type_table = STRING, length = 1}, unit = 0x07},
	{cell = {type_table = STRING, length = 1}, unit = 0x08},
	{cell = {type_table = STRING, length = 1}, unit = 0x09},
	{cell = {type_table = STRING, length = 1}, unit = 0x0a},
	{cell = {type_table = STRING, length = 1}, unit = 0x0b},
	{cell = {type_table = STRING, length = 1}, unit = 0x0c},
	{cell = {type_table = STRING, length = 1}, unit = 0x0d},
	{cell = {type_table = STRING, length = 1}, unit = 0x0e},
	{cell = {type_table = STRING, length = 1}, unit = 0x0f},
	{cell = {type_table = STRING, length = 1}, unit = 0x10},
	{cell = {type_table = STRING, length = 1}, unit = 0x11},
	{cell = {type_table = STRING, length = 1}, unit = 0x12},
	{cell = {type_table = STRING, length = 1}, unit = 0x13},
	{cell = {type_table = STRING, length = 1}, unit = 0x14},
	{cell = {type_table = STRING, length = 1}, unit = 0x15},
	{cell = {type_table = STRING, length = 1}, unit = 0x16},
	{cell = {type_table = STRING, length = 1}, unit = 0x17},
	{cell = {type_table = STRING, length = 1}, unit = 0x18},
	{cell = {type_table = STRING, length = 1}, unit = 0x19},
	{cell = {type_table = STRING, length = 1}, unit = 0x1a},
	{cell = {type_table = STRING, length = 1}, unit = 0x1b},
	{cell = {type_table = STRING, length = 1}, unit = 0x1c},
	{cell = {type_table = STRING, length = 1}, unit = 0x1d},
	{cell = {type_table = STRING, length = 1}, unit = 0x1e},
	{cell = {type_table = STRING, length = 1}, unit = 0x1f},
	{cell = {type_table = STRING, length = 1}, unit = 0x20},
	{cell = {type_table = STRING, length = 1}, unit = 0x21},
	{cell = {type_table = STRING, length = 1}, unit = 0x22},
	{cell = {type_table = STRING, length = 1}, unit = 0x23},
	{cell = {type_table = STRING, length = 1}, unit = 0x24},
	{cell = {type_table = STRING, length = 1}, unit = 0x25},
	{cell = {type_table = STRING, length = 1}, unit = 0x26},
	{cell = {type_table = STRING, length = 1}, unit = 0x27},
	{cell = {type_table = STRING, length = 1}, unit = 0x28},
	{cell = {type_table = STRING, length = 1}, unit = 0x29},
	{cell = {type_table = STRING, length = 1}, unit = 0x2a},
	{cell = {type_table = STRING, length = 1}, unit = 0x2b},
	{cell = {type_table = STRING, length = 1}, unit = 0x2c},
	{cell = {type_table = STRING, length = 1}, unit = 0x2d},
	{cell = {type_table = STRING, length = 1}, unit = 0x2e},
	{cell = {type_table = STRING, length = 1}, unit = 0x2f},
	{cell = {type_table = STRING, length = 1}, unit = 0x30},
	{cell = {type_table = STRING, length = 1}, unit = 0x31},
	{cell = {type_table = STRING, length = 1}, unit = 0x32},
	{cell = {type_table = STRING, length = 1}, unit = 0x33},
	{cell = {type_table = STRING, length = 1}, unit = 0x34},
	{cell = {type_table = STRING, length = 1}, unit = 0x35},
	{cell = {type_table = STRING, length = 1}, unit = 0x36},
	{cell = {type_table = STRING, length = 1}, unit = 0x37},
	{cell = {type_table = STRING, length = 1}, unit = 0x38},
	{cell = {type_table = STRING, length = 1}, unit = 0x39},
	{cell = {type_table = STRING, length = 1}, unit = 0x3a},
	{cell = {type_table = STRING, length = 1}, unit = 0x3b},
	{cell = {type_table = STRING, length = 1}, unit = 0x3c},
	{cell = {type_table = STRING, length = 1}, unit = 0x3d},
	{cell = {type_table = STRING, length = 1}, unit = 0x3e},
	{cell = {type_table = STRING, length = 1}, unit = 0x3f},
	{cell = {type_table = STRING, length = 1}, unit = 0x40},
	{cell = {type_table = STRING, length = 1}, unit = 0x41},
	{cell = {type_table = STRING, length = 1}, unit = 0x42},
	{cell = {type_table = STRING, length = 1}, unit = 0x43},
	{cell = {type_table = STRING, length = 1}, unit = 0x44},
	{cell = {type_table = STRING, length = 1}, unit = 0x45},
	{cell = {type_table = STRING, length = 1}, unit = 0x46},
	{cell = {type_table = STRING, length = 1}, unit = 0x47},
	{cell = {type_table = STRING, length = 1}, unit = 0x48},
	{cell = {type_table = STRING, length = 1}, unit = 0x49},
	{cell = {type_table = STRING, length = 1}, unit = 0x4a},
	{cell = {type_table = STRING, length = 1}, unit = 0x4b},
	{cell = {type_table = STRING, length = 1}, unit = 0x4c},
	{cell = {type_table = STRING, length = 1}, unit = 0x4d},
	{cell = {type_table = STRING, length = 1}, unit = 0x4e},
	{cell = {type_table = STRING, length = 1}, unit = 0x4f},
	{cell = {type_table = STRING, length = 1}, unit = 0x50},
	{cell = {type_table = STRING, length = 1}, unit = 0x51},
	{cell = {type_table = STRING, length = 1}, unit = 0x52},
	{cell = {type_table = STRING, length = 1}, unit = 0x53},
	{cell = {type_table = STRING, length = 1}, unit = 0x54},
	{cell = {type_table = STRING, length = 1}, unit = 0x55},
	{cell = {type_table = STRING, length = 1}, unit = 0x56},
	{cell = {type_table = STRING, length = 1}, unit = 0x57},
	{cell = {type_table = STRING, length = 1}, unit = 0x58},
	{cell = {type_table = STRING, length = 1}, unit = 0x59},
	{cell = {type_table = STRING, length = 1}, unit = 0x5a},
	{cell = {type_table = STRING, length = 1}, unit = 0x5b},
	{cell = {type_table = STRING, length = 1}, unit = 0x5c},
	{cell = {type_table = STRING, length = 1}, unit = 0x5d},
	{cell = {type_table = STRING, length = 1}, unit = 0x5e},
	{cell = {type_table = STRING, length = 1}, unit = 0x5f},
	{cell = {type_table = STRING, length = 1}, unit = 0x60},
	{cell = {type_table = STRING, length = 1}, unit = 0x61},
	{cell = {type_table = STRING, length = 1}, unit = 0x62},
	{cell = {type_table = STRING, length = 1}, unit = 0x63},
	{cell = {type_table = STRING, length = 1}, unit = 0x64},
	{cell = {type_table = STRING, length = 1}, unit = 0x65},
	{cell = {type_table = STRING, length = 1}, unit = 0x66},
	{cell = {type_table = STRING, length = 1}, unit = 0x67},
	{cell = {type_table = STRING, length = 1}, unit = 0x68},
	{cell = {type_table = STRING, length = 1}, unit = 0x69},
	{cell = {type_table = STRING, length = 1}, unit = 0x6a},
	{cell = {type_table = STRING, length = 1}, unit = 0x6b},
	{cell = {type_table = STRING, length = 1}, unit = 0x6c},
	{cell = {type_table = STRING, length = 1}, unit = 0x6d},
	{cell = {type_table = STRING, length = 1}, unit = 0x6e},
	{cell = {type_table = STRING, length = 1}, unit = 0x6f},
	{cell = {type_table = STRING, length = 1}, unit = 0x70},
	{cell = {type_table = STRING, length = 1}, unit = 0x71},
	{cell = {type_table = STRING, length = 1}, unit = 0x72},
	{cell = {type_table = STRING, length = 1}, unit = 0x73},
	{cell = {type_table = STRING, length = 1}, unit = 0x74},
	{cell = {type_table = STRING, length = 1}, unit = 0x75},
	{cell = {type_table = STRING, length = 1}, unit = 0x76},
	{cell = {type_table = STRING, length = 1}, unit = 0x77},
	{cell = {type_table = STRING, length = 1}, unit = 0x78},
	{cell = {type_table = STRING, length = 1}, unit = 0x79},
	{cell = {type_table = STRING, length = 1}, unit = 0x7a},
	{cell = {type_table = STRING, length = 1}, unit = 0x7b},
	{cell = {type_table = STRING, length = 1}, unit = 0x7c},
	{cell = {type_table = STRING, length = 1}, unit = 0x7d},
	{cell = {type_table = STRING, length = 1}, unit = 0x7e},
	{cell = {type_table = STRING, length = 1}, unit = 0x7f},
}
